# SEC 2021

In [1]:
import pandas as pd

In [6]:
url = 'https://www.sports-reference.com/cfb/schools/georgia/2021-schedule.html'
url1 = 'https://www.sports-reference.com/cfb/schools/kentucky/2021-schedule.html'
url2 = 'https://www.sports-reference.com/cfb/schools/tennessee/2021-schedule.html'
url3 = 'https://www.sports-reference.com/cfb/schools/south-carolina/2021-schedule.html'
url4 = 'https://www.sports-reference.com/cfb/schools/missouri/2021-schedule.html'
url5 = 'https://www.sports-reference.com/cfb/schools/florida/2021-schedule.html'
url6 = 'https://www.sports-reference.com/cfb/schools/vanderbilt/2021-schedule.html'
url7 = 'https://www.sports-reference.com/cfb/schools/alabama/2021-schedule.html'
url8 = 'https://www.sports-reference.com/cfb/schools/mississippi/2021-schedule.html'
url9 = 'https://www.sports-reference.com/cfb/schools/arkansas/2021-schedule.html'
url10 = 'https://www.sports-reference.com/cfb/schools/texas-am/2021-schedule.html'
url11 = 'https://www.sports-reference.com/cfb/schools/mississippi-state/2021-schedule.html'
url12 = 'https://www.sports-reference.com/cfb/schools/auburn/2021-schedule.html'
url13 = 'https://www.sports-reference.com/cfb/schools/louisiana-state/2021-schedule.html'

url14 = 'https://www.sports-reference.com/cfb/schools/tulane/2021-schedule.html'
url15 = 'https://www.sports-reference.com/cfb/schools/south-florida/2021-schedule.html'
url16 = 'https://www.sports-reference.com/cfb/schools/temple/2021-schedule.html'
url17 = 'https://www.sports-reference.com/cfb/schools/navy/2021-schedule.html'
url18 = 'https://www.sports-reference.com/cfb/schools/memphis/2021-schedule.html'
url19 = 'https://www.sports-reference.com/cfb/schools/southern-methodist/2021-schedule.html'
url20 = 'https://www.sports-reference.com/cfb/schools/tulsa/2021-schedule.html'
url21 = 'https://www.sports-reference.com/cfb/schools/east-carolina/2021-schedule.html'
url22 = 'https://www.sports-reference.com/cfb/schools/central-florida/2021-schedule.html'
url23 = 'https://www.sports-reference.com/cfb/schools/houston/2021-schedule.html'
url24 = 'https://www.sports-reference.com/cfb/schools/cincinnati/2021-schedule.html'

url25 = 'https://www.sports-reference.com/cfb/schools/texas/2021-schedule.html'
url26 = 'https://www.sports-reference.com/cfb/schools/texas-christian/2021-schedule.html'
url27 = 'https://www.sports-reference.com/cfb/schools/kansas/2021-schedule.html'
url28 = 'https://www.sports-reference.com/cfb/schools/baylor/2021-schedule.html'
url29 = 'https://www.sports-reference.com/cfb/schools/oklahoma-state/2021-schedule.html'
url30 = 'https://www.sports-reference.com/cfb/schools/oklahoma/2021-schedule.html'
url31 = 'https://www.sports-reference.com/cfb/schools/iowa-state/2021-schedule.html'
url32 = 'https://www.sports-reference.com/cfb/schools/kansas-state/2021-schedule.html'
url33 = 'https://www.sports-reference.com/cfb/schools/west-virginia/2021-schedule.html'
url34 = 'https://www.sports-reference.com/cfb/schools/texas-tech/2021-schedule.html'

url35 = 'https://www.sports-reference.com/cfb/schools/minnesota/2021-schedule.html'
url36 = 'https://www.sports-reference.com/cfb/schools/iowa/2021-schedule.html'
url37 = 'https://www.sports-reference.com/cfb/schools/indiana/2021-schedule.html'
url38 = 'https://www.sports-reference.com/cfb/schools/rutgers/2021-schedule.html'
url39 = 'https://www.sports-reference.com/cfb/schools/maryland/2021-schedule.html'
url40 = 'https://www.sports-reference.com/cfb/schools/penn-state/2021-schedule.html'
url41 = 'https://www.sports-reference.com/cfb/schools/michigan-state/2021-schedule.html'
url42 = 'https://www.sports-reference.com/cfb/schools/ohio-state/2021-schedule.html'
url43 = 'https://www.sports-reference.com/cfb/schools/michigan/2021-schedule.html'
url44 = 'https://www.sports-reference.com/cfb/schools/northwestern/2021-schedule.html'
url45 = 'https://www.sports-reference.com/cfb/schools/nebraska/2021-schedule.html'
url46 = 'https://www.sports-reference.com/cfb/schools/illinois/2021-schedule.html'
url47 = 'https://www.sports-reference.com/cfb/schools/wisconsin/2021-schedule.html'
url48 = 'https://www.sports-reference.com/cfb/schools/purdue/2021-schedule.html'

url49 = 'https://www.sports-reference.com/cfb/schools/florida-international/2021-schedule.html'
url50 = 'https://www.sports-reference.com/cfb/schools/florida-atlantic/2021-schedule.html'
url51 = 'https://www.sports-reference.com/cfb/schools/charlotte/2021-schedule.html'
url52 = 'https://www.sports-reference.com/cfb/schools/middle-tennessee-state/2021-schedule.html'
url53 = 'https://www.sports-reference.com/cfb/schools/old-dominion/2021-schedule.html'
url54 = 'https://www.sports-reference.com/cfb/schools/marshall/2021-schedule.html'
url55 = 'https://www.sports-reference.com/cfb/schools/western-kentucky/2021-schedule.html'
url56 = 'https://www.sports-reference.com/cfb/schools/southern-mississippi/2021-schedule.html'
url57 = 'https://www.sports-reference.com/cfb/schools/louisiana-tech/2021-schedule.html'
url58 = 'https://www.sports-reference.com/cfb/schools/rice/2021-schedule.html'
url59 = 'https://www.sports-reference.com/cfb/schools/texas-el-paso/2021-schedule.html'
url60 = 'https://www.sports-reference.com/cfb/schools/north-texas/2021-schedule.html'
url61 = 'https://www.sports-reference.com/cfb/schools/alabama-birmingham/2021-schedule.html'
url62 = 'https://www.sports-reference.com/cfb/schools/texas-san-antonio/2021-schedule.html'

url63 = 'https://www.sports-reference.com/cfb/schools/brigham-young/2021-schedule.html'
url64 = 'https://www.sports-reference.com/cfb/schools/army/2021-schedule.html'
url65 = 'https://www.sports-reference.com/cfb/schools/connecticut/2021-schedule.html'
url66 = 'https://www.sports-reference.com/cfb/schools/massachusetts/2021-schedule.html'
url67 = 'https://www.sports-reference.com/cfb/schools/liberty/2021-schedule.html'
url68 = 'https://www.sports-reference.com/cfb/schools/new-mexico-state/2021-schedule.html'
url69 = 'https://www.sports-reference.com/cfb/schools/notre-dame/2021-schedule.html'

url70 = 'https://www.sports-reference.com/cfb/schools/akron/2021-schedule.html'
url71 = 'https://www.sports-reference.com/cfb/schools/buffalo/2021-schedule.html'
url72 = 'https://www.sports-reference.com/cfb/schools/bowling-green-state/2021-schedule.html'
url73 = 'https://www.sports-reference.com/cfb/schools/ohio/2021-schedule.html'
url74 = 'https://www.sports-reference.com/cfb/schools/miami-oh/2021-schedule.html'
url75 = 'https://www.sports-reference.com/cfb/schools/kent-state/2021-schedule.html'
url76 = 'https://www.sports-reference.com/cfb/schools/ball-state/2021-schedule.html'
url77 = 'https://www.sports-reference.com/cfb/schools/eastern-michigan/2021-schedule.html'
url78 = 'https://www.sports-reference.com/cfb/schools/western-michigan/2021-schedule.html'
url79 = 'https://www.sports-reference.com/cfb/schools/toledo/2021-schedule.html'
url80 = 'https://www.sports-reference.com/cfb/schools/central-michigan/2021-schedule.html'
url81 = 'https://www.sports-reference.com/cfb/schools/northern-illinois/2021-schedule.html'

url82 = 'https://www.sports-reference.com/cfb/schools/utah-state/2021-schedule.html'
url83 = 'https://www.sports-reference.com/cfb/schools/air-force/2021-schedule.html'
url84 = 'https://www.sports-reference.com/cfb/schools/boise-state/2021-schedule.html'
url85 = 'https://www.sports-reference.com/cfb/schools/wyoming/2021-schedule.html'
url86 = 'https://www.sports-reference.com/cfb/schools/colorado-state/2021-schedule.html'
url87 = 'https://www.sports-reference.com/cfb/schools/new-mexico/2021-schedule.html'
url88 = 'https://www.sports-reference.com/cfb/schools/nevada-las-vegas/2021-schedule.html'
url89 = 'https://www.sports-reference.com/cfb/schools/san-jose-state/2021-schedule.html'
url90 = 'https://www.sports-reference.com/cfb/schools/hawaii/2021-schedule.html'
url91 = 'https://www.sports-reference.com/cfb/schools/nevada/2021-schedule.html'
url92 = 'https://www.sports-reference.com/cfb/schools/fresno-state/2021-schedule.html'
url93 = 'https://www.sports-reference.com/cfb/schools/san-diego-state/2021-schedule.html'

url94 = 'https://www.sports-reference.com/cfb/schools/stanford/2021-schedule.html'
url95 = 'https://www.sports-reference.com/cfb/schools/washington/2021-schedule.html'
url96 = 'https://www.sports-reference.com/cfb/schools/california/2021-schedule.html'
url97 = 'https://www.sports-reference.com/cfb/schools/oregon-state/2021-schedule.html'
url98 = 'https://www.sports-reference.com/cfb/schools/washington-state/2021-schedule.html'
url99 = 'https://www.sports-reference.com/cfb/schools/oregon/2021-schedule.html'
url100 = 'https://www.sports-reference.com/cfb/schools/arizona/2021-schedule.html'
url101 = 'https://www.sports-reference.com/cfb/schools/southern-california/2021-schedule.html'
url102 = 'https://www.sports-reference.com/cfb/schools/colorado/2021-schedule.html'
url103 = 'https://www.sports-reference.com/cfb/schools/arizona-state/2021-schedule.html'
url104 = 'https://www.sports-reference.com/cfb/schools/ucla/2021-schedule.html'
url105 = 'https://www.sports-reference.com/cfb/schools/utah/2021-schedule.html'

In [7]:
rawdat = pd.read_html(url) + pd.read_html(url1) + pd.read_html(url2) + pd.read_html(url3) + pd.read_html(url4) + pd.read_html(url5) + pd.read_html(url6) + pd.read_html(url7) + pd.read_html(url8) + pd.read_html(url9) + pd.read_html(url10) + pd.read_html(url11) + pd.read_html(url12) + pd.read_html(url13) + pd.read_html(url14) + pd.read_html(url15) + pd.read_html(url16) + pd.read_html(url17) + pd.read_html(url18) + pd.read_html(url19) + pd.read_html(url20) + pd.read_html(url21) + pd.read_html(url22) + pd.read_html(url23) + pd.read_html(url24) + pd.read_html(url25) + pd.read_html(url26) + pd.read_html(url27) + pd.read_html(url28) + pd.read_html(url29) + pd.read_html(url30) + pd.read_html(url31) + pd.read_html(url32) + pd.read_html(url33) + pd.read_html(url34) + pd.read_html(url35) + pd.read_html(url36) + pd.read_html(url37) + pd.read_html(url38) + pd.read_html(url39) + pd.read_html(url40) + pd.read_html(url41) + pd.read_html(url42) + pd.read_html(url43) + pd.read_html(url44) + pd.read_html(url45) + pd.read_html(url46) + pd.read_html(url47) + pd.read_html(url48) + pd.read_html(url49) + pd.read_html(url50) + pd.read_html(url51) + pd.read_html(url52) + pd.read_html(url53) + pd.read_html(url54) + pd.read_html(url55) + pd.read_html(url56) + pd.read_html(url57) + pd.read_html(url58) + pd.read_html(url59) + pd.read_html(url60) + pd.read_html(url61) + pd.read_html(url62) + pd.read_html(url63) + pd.read_html(url64) + pd.read_html(url65) + pd.read_html(url66) + pd.read_html(url67) + pd.read_html(url68) + pd.read_html(url69) + pd.read_html(url70) + pd.read_html(url71) + pd.read_html(url72) + pd.read_html(url73) + pd.read_html(url74) + pd.read_html(url75) + pd.read_html(url76) + pd.read_html(url77) + pd.read_html(url78) + pd.read_html(url79) + pd.read_html(url80) + pd.read_html(url81) + pd.read_html(url82) + pd.read_html(url83) + pd.read_html(url84) + pd.read_html(url85) + pd.read_html(url86) + pd.read_html(url87) + pd.read_html(url88) + pd.read_html(url89) + pd.read_html(url90) + pd.read_html(url91) + pd.read_html(url92) + pd.read_html(url93) + pd.read_html(url94) + pd.read_html(url95) + pd.read_html(url96) + pd.read_html(url97) + pd.read_html(url98) + pd.read_html(url99) + pd.read_html(url100) + pd.read_html(url101) + pd.read_html(url102) + pd.read_html(url103) + pd.read_html(url104) + pd.read_html(url105)

In [158]:
alldata = pd.concat([rawdat[1], rawdat[3], rawdat[4], rawdat[5], rawdat[6], rawdat[8], rawdat[9], rawdat[11], rawdat[13], rawdat[15], rawdat[17], rawdat[18], rawdat[20], rawdat[22], rawdat[23], rawdat[24], rawdat[25], rawdat[26], rawdat[27], rawdat[29], rawdat[30], rawdat[31], rawdat[32], rawdat[34], rawdat[36], rawdat[38], rawdat[39], rawdat[40], rawdat[42], rawdat[44], rawdat[46], rawdat[48], rawdat[50], rawdat[51], rawdat[52], rawdat[53], rawdat[55], rawdat[57], rawdat[58], rawdat[59], rawdat[61], rawdat[63], rawdat[65], rawdat[67], rawdat[68], rawdat[69], rawdat[70], rawdat[72], rawdat[74], rawdat[75], rawdat[76], rawdat[77], rawdat[78], rawdat[79], rawdat[80], rawdat[81], rawdat[82], rawdat[83], rawdat[84], rawdat[85], rawdat[86], rawdat[87], rawdat[89], rawdat[91], rawdat[92], rawdat[93], rawdat[94], rawdat[95], rawdat[96], rawdat[98], 	rawdat[99], 	rawdat[100], 	rawdat[101], 	rawdat[102], 	rawdat[103], 	rawdat[104], 	rawdat[105], 	rawdat[106], 	rawdat[107], 	rawdat[108], 	rawdat[109], 	rawdat[110], 	rawdat[112], 	rawdat[113], 	rawdat[114], 	rawdat[115], 	rawdat[116], 	rawdat[117], 	rawdat[118], 	rawdat[119], 	rawdat[120], 	rawdat[121], 	rawdat[123], 	rawdat[125], 	rawdat[126], 	rawdat[128], 	rawdat[129], 	rawdat[130], 	rawdat[131], 	rawdat[133], 	rawdat[134], 	rawdat[136], 	rawdat[137], 	rawdat[139], 	rawdat[141], 	rawdat[143]])

In [160]:
alldata.to_excel('Rawdata.xlsx', sheet_name='sheet1', index=False)

In [164]:
alldata.drop(columns = ['G', 'Date', 'Time', 'Day', 'W', 'L', 'Streak', 'Notes'], inplace=True)

In [167]:
alldata.rename(columns ={'Unnamed: 5' : 'HomeAway', 'Unnamed: 8' : 'WL'}, inplace=True)

In [173]:
#alldata.fillna('H', inplace=True)
alldata.head()

        School HomeAway        Opponent  Conf WL  Pts  Opp
0  (5) Georgia        N     (3) Clemson   ACC  W   10    3
1  (2) Georgia        H             UAB  CUSA  W   56    7
2  (2) Georgia        H  South Carolina   SEC  W   40   13
3  (2) Georgia        @      Vanderbilt   SEC  W   62    0
4  (2) Georgia        H    (8) Arkansas   SEC  W   37    0

In [175]:
alldata['School'] = alldata['School'].str.replace("[5, 3, 11, 25, 13, 20, 5, 2, 17, 10, 20, 8, 21, 6, 15, 17, ), (, 16, 18, 24, 23, 7, 2, 14, 9, 19, 11, 22, 10, 12, 19,]", "")

C:\Users\vmidh\AppData\Local\Temp/ipykernel_3348/2882044669.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  alldata['School'] = alldata['School'].str.replace("[5, 3, 11, 25, 13, 20, 5, 2, 17, 10, 20, 8, 21, 6, 15, 17, ), (, 16, 18, 24, 23, 7, 2, 14, 9, 19, 11, 22, 10, 12, 19,]", "")

In [179]:
alldata['School'] = alldata['School'].str.replace("\xa0", "")

In [227]:
#alldata.loc[(alldata.HomeAway == "@") | (alldata.WL == "W"), "Rank"] = 1
alldata['Rank'] = alldata['Rank'].fillna(0)
alldata

     School HomeAway        Opponent     Conf WL  Pts  Opp  Rank
0   Georgia        N     (3) Clemson      ACC  W   10    3   1.0
1   Georgia        H             UAB     CUSA  W   56    7   1.0
2   Georgia        H  South Carolina      SEC  W   40   13   1.0
3   Georgia        @      Vanderbilt      SEC  W   62    0   1.0
4   Georgia        H    (8) Arkansas      SEC  W   37    0   1.0
..      ...      ...             ...      ... ..  ...  ...   ...
9      Utah        @         Arizona   Pac-12  W   38   29   1.0
10     Utah        H      (4) Oregon   Pac-12  W   38    7   1.0
11     Utah        H        Colorado   Pac-12  W   28   13   1.0
12     Utah        N     (10) Oregon   Pac-12  W   38   10   1.0
13     Utah        N  (7) Ohio State  Big Ten  L   45   48   0.0

[1355 rows x 8 columns]

In [ ]:
#filt = alldata.Rank == 1
#filt1 = alldata.Conf == "SEC"

In [228]:
alldata['weight'] = alldata['Rank'] + (alldata['Pts'] - alldata['Opp'])

In [229]:
alldata.head()

    School HomeAway        Opponent  Conf WL  Pts  Opp  Rank  weight
0  Georgia        N     (3) Clemson   ACC  W   10    3   1.0     8.0
1  Georgia        H             UAB  CUSA  W   56    7   1.0    50.0
2  Georgia        H  South Carolina   SEC  W   40   13   1.0    28.0
3  Georgia        @      Vanderbilt   SEC  W   62    0   1.0    63.0
4  Georgia        H    (8) Arkansas   SEC  W   37    0   1.0    38.0

In [232]:
x = alldata.groupby(['School', 'Conf']).weight.sum()

In [235]:
cl = pd.DataFrame(x)

In [238]:
cl.reset_index(inplace = True)

In [242]:
cl.rename(columns = {'School': 'Team'}, inplace=True)
Cleanup1 = cl

In [271]:
Cleanup1.loc[(Cleanup1.Team == 'Virginia') | (Cleanup1.Team =='Syracuse') | (Cleanup1.Team =='Georgia Tech') | (Cleanup1.Team =='Duke') | (Cleanup1.Team == 'Florida St.') | (Cleanup1.Team == 'Virginia Tech') | (Cleanup1.Team == 'Clemson') | (Cleanup1.Team == 'Louisville') | (Cleanup1.Team == 'Pittsburg') | (Cleanup1.Team == 'Wake Forest') | (Cleanup1.Team == 'Boston College') | (Cleanup1.Team == 'North Carolina') | (Cleanup1.Team == 'Miami (FL)')  | (Cleanup1.Team == 'NC State'), 'Conference'] = 'ACC'
Cleanup1.loc[(Cleanup1.Team == 'IowaState') | (Cleanup1.Team =='Kansas') | (Cleanup1.Team =='OklahomaState') | (Cleanup1.Team =='WestVirginia') | (Cleanup1.Team == 'TexasTech') | (Cleanup1.Team == 'KansasState') | (Cleanup1.Team == 'Texas') | (Cleanup1.Team == 'Baylor') | (Cleanup1.Team == 'TexasChristian') | (Cleanup1.Team == 'Oklahoma'), 'Conference'] = 'BIG 12'
Cleanup1.loc[(Cleanup1.Team == 'Northwestern') | (Cleanup1.Team =='Wisconsin') | (Cleanup1.Team =='Iowa') | (Cleanup1.Team =='Nebraska') | (Cleanup1.Team == 'Purdue') | (Cleanup1.Team == 'PennState') | (Cleanup1.Team == 'MichiganState') | (Cleanup1.Team == 'Minnesota') | (Cleanup1.Team == 'Illinois') | (Cleanup1.Team == 'Rutgers') | (Cleanup1.Team == 'Indiana') | (Cleanup1.Team == 'Maryland') | (Cleanup1.Team == 'Michigan') | (Cleanup1.Team == 'OhioState'),  'Conference'] = 'BIG10'
Cleanup1.loc[(Cleanup1.Team == 'Memphis') | (Cleanup1.Team =='UCF') | (Cleanup1.Team =='Cincinnati') | (Cleanup1.Team =='Tulsa') | (Cleanup1.Team == 'SMU') | (Cleanup1.Team == 'Tulane') | (Cleanup1.Team == 'Houston') | (Cleanup1.Team == 'Temple') | (Cleanup1.Team == 'SouthFlorida') | (Cleanup1.Team == 'Navy') | (Cleanup1.Team == 'EastCarolina') ,  'Conference'] = 'AA'
Cleanup1.loc[(Cleanup1.Team == 'SanJoseState') | (Cleanup1.Team =='Wyoming') | (Cleanup1.Team =='Nevada-LasVegas') | (Cleanup1.Team =='UtahState') | (Cleanup1.Team == 'Nevada') | (Cleanup1.Team == 'ColoradoState') | (Cleanup1.Team == 'Hawaii') | (Cleanup1.Team == 'NewMexico') | (Cleanup1.Team == 'FresnoState') | (Cleanup1.Team == 'SanDiegoState') | (Cleanup1.Team == 'BoiseState') | (Cleanup1.Team == 'AirForce'),  'Conference'] = 'MountainWest'
Cleanup1.loc[(Cleanup1.Team == 'OregonState') | (Cleanup1.Team =='WashingtonState') | (Cleanup1.Team =='Stanford') | (Cleanup1.Team =='Utah') | (Cleanup1.Team == 'California') | (Cleanup1.Team == 'Arizona') | (Cleanup1.Team == 'ArizonaState') | (Cleanup1.Team == 'Washington') | (Cleanup1.Team == 'Colorado') | (Cleanup1.Team == 'Oregon') | (Cleanup1.Team == 'UCLA') | (Cleanup1.Team == 'USC'),  'Conference'] = 'Pac12'
Cleanup1.loc[(Cleanup1.Team == 'Troy') | (Cleanup1.Team =='App State') | (Cleanup1.Team =='Coastal Carolina') | (Cleanup1.Team =='Arkansas St.') | (Cleanup1.Team == 'Georgia St.') | (Cleanup1.Team == 'Texas St.') | (Cleanup1.Team == 'Ga. Southern') | (Cleanup1.Team == 'Louisiana') | (Cleanup1.Team == 'South Alabama') | (Cleanup1.Team == 'ULM'),  'Conference'] = 'SUNBELT'
Cleanup1.loc[(Cleanup1.Team == 'BowlingGreenState') | (Cleanup1.Team =='MiamiOH') | (Cleanup1.Team =='Buffalo') | (Cleanup1.Team =='Ohio') | (Cleanup1.Team == 'BallState') | (Cleanup1.Team == 'KentState') | (Cleanup1.Team == 'Toledo') | (Cleanup1.Team == 'Akron') | (Cleanup1.Team ==  'EasternMichigan') | (Cleanup1.Team == 'CentralMichigan') | (Cleanup1.Team == 'WesternMichigan') | (Cleanup1.Team == 'NorthernIllinois'),  'Conference'] = 'Mid-American'
Cleanup1.loc[(Cleanup1.Team == 'NorthTexas') | (Cleanup1.Team == 'MiddleTennesseeState') | (Cleanup1.Team =='Marshall') | (Cleanup1.Team =='UTEP') | (Cleanup1.Team == 'OldDominion') | (Cleanup1.Team == 'UAB') | (Cleanup1.Team == 'WesternKentucky') | (Cleanup1.Team == 'Charlotte') | (Cleanup1.Team == 'FloridaAtlantic') | (Cleanup1.Team == 'Rice') | (Cleanup1.Team == 'FloridaInternational') | (Cleanup1.Team == 'UTSA') | (Cleanup1.Team == 'SouthernMississippi')  | (Cleanup1.Team == 'LouisianaTech'), 'Conference'] = 'ConfUSA'

In [289]:
#f = Cleanup1.Conference.isna()
#Cleanup1[f].Team.unique()

Empty DataFrame
Columns: [Team, Conf, weight, Conference]
Index: []

In [284]:
Cleanup1.loc[(Cleanup1.Team == 'Alabama') | (Cleanup1.Team =='Arkansas') | (Cleanup1.Team =='Auburn') | (Cleanup1.Team =='Florida') | (Cleanup1.Team == 'Georgia') | (Cleanup1.Team == 'Kentucky') | (Cleanup1.Team == 'LSU') | (Cleanup1.Team == 'MississippiState') | (Cleanup1.Team == 'Missouri') | (Cleanup1.Team == 'OleMiss') | (Cleanup1.Team == 'SouthCarolina') | (Cleanup1.Team == 'Tennessee') | (Cleanup1.Team == 'TexasA&M')  | (Cleanup1.Team == 'Vanderbilt'), 'Conference'] = 'SEC'
Cleanup1.loc[(Cleanup1.Team == 'Army') | (Cleanup1.Team =='BYU') | (Cleanup1.Team =='Connecticut') | (Cleanup1.Team =='Liberty') | (Cleanup1.Team == 'Massachusetts') | (Cleanup1.Team == 'NewMexicoState') | (Cleanup1.Team == 'NotreDame'), 'Conference'] = 'Independent'

In [296]:
#Cleanup1.rename(columns = {'Team': 'School', 'Conference': 'BASE'}, inplace=True)
Cleanup1.head()

     School      Conf  weight          BASE
0  AirForce       ACC     4.0  MountainWest
1  AirForce  American    21.0  MountainWest
2  AirForce      CUSA    25.0  MountainWest
3  AirForce       Ind    -7.0  MountainWest
4  AirForce       MWC    91.0  MountainWest

In [301]:
#Cleanup1.Conf.unique()
#'ACC', 'American', 'CUSA', 'Ind', 'MWC', 'Non-Major', 'Big Ten','MAC', 'SEC', 'Pac-12', 'Big 12', 'Sun Belt'
#Cleanup1.BASE.unique()
#MountainWest', 'Mid-American', 'SEC', 'Pac12', 'Independent','BIG 12', 'ConfUSA', 'AA', 'BIG10'
Cleanup1.BASE = Cleanup1.BASE.str.replace('MountainWest','MWC')
checkp = Cleanup1

In [307]:
#checkp.BASE = checkp.BASE.str.replace('AA', 'American').str.replace('ConfUSA', 'CUSA')
checkp.BASE = checkp.BASE.str.replace('Independent', 'Ind').str.replace('ConfUSA', 'CUSA').str.replace('BIG10', 'Big Ten').str.replace('Mid-American', 'MAC').str.replace('Pac12', 'Pac-12').str.replace('BIG 12', 'Big 12').str.replace('BIG 12', 'Big 12')

In [308]:
checkp

        School       Conf  weight     BASE
0     AirForce        ACC     4.0      MWC
1     AirForce   American    21.0      MWC
2     AirForce       CUSA    25.0      MWC
3     AirForce        Ind    -7.0      MWC
4     AirForce        MWC    91.0      MWC
..         ...        ...     ...      ...
524  Wisconsin     Pac-12     8.0  Big Ten
525    Wyoming        Ind     3.0      MWC
526    Wyoming        MAC    57.0      MWC
527    Wyoming        MWC   -32.0      MWC
528    Wyoming  Non-Major     4.0      MWC

[529 rows x 4 columns]

In [310]:
checkp.loc[(checkp.Conf == checkp.BASE), 'Interleague'] = checkp['weight']

In [314]:
checkp.loc[(checkp.Conf == 'SEC'), 'SEC'] = checkp['weight']
checkp.loc[(checkp.Conf == 'ACC'), 'ACC'] = checkp['weight']
checkp.loc[(checkp.Conf == 'Big 12'), 'Big 12'] = checkp['weight']
checkp.loc[(checkp.Conf == 'CUSA'), 'CUSA'] = checkp['weight']
checkp.loc[(checkp.Conf == 'Ind'), 'Independent'] = checkp['weight']
checkp.loc[(checkp.Conf == 'MAC'), 'MidAmerican'] = checkp['weight']
checkp.loc[(checkp.Conf == 'Pac-12'), 'Pac-12'] = checkp['weight']
checkp.loc[(checkp.Conf == 'Sun Belt'), 'Sun Belt'] = checkp['weight']
checkp.loc[(checkp.Conf == 'Big Ten'), 'Big10'] = checkp['weight']
checkp.loc[(checkp.Conf == 'MWC'), 'MountainWest'] = checkp['weight']
checkp.loc[(checkp.Conf == 'Non-Major'), 'Other'] = checkp['weight']

In [338]:
#checkp.Conf.unique()
checkp.loc[(checkp.Conf == 'American'), 'AA'] = checkp['weight']

In [357]:
checkp.Conf.unique()

array(['ACC', 'American', 'CUSA', 'Ind', 'MWC', 'Non-Major', 'Big Ten',
       'MAC', 'SEC', 'Pac-12', 'Big 12', 'Sun Belt'], dtype=object)

In [350]:
conf2 = checkp.groupby(['BASE', 'School'])['Interleague', 'SEC', 'ACC', 'Big 12', 'CUSA', 'Independent', 'MidAmerican', 'Pac-12', 'Sun Belt', 'Big10', 'MountainWest', 'AA', 'Other'].sum()

C:\Users\vmidh\AppData\Local\Temp/ipykernel_3348/410142189.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  conf2 = checkp.groupby(['BASE', 'School'])['Interleague', 'SEC', 'ACC', 'Big 12', 'CUSA', 'Independent', 'MidAmerican', 'Pac-12', 'Sun Belt', 'Big10', 'MountainWest', 'AA', 'Other'].sum()

In [353]:
allc = pd.DataFrame(conf2)

In [354]:
allc.reset_index(inplace=True)

In [335]:
s = allc.BASE == 'SEC'

In [355]:
allc

,BASE,School,Interleague,SEC,ACC,Big 12,CUSA,Independent,MidAmerican,Pac-12,Sun Belt,Big10,MountainWest,AA,Other
0,American,Cincinnati,215.0,-21.0,0.0,0.0,0.0,12.0,36.0,0.0,0.0,15.0,0.0,215.0,36.0
1,American,EastCarolina,58.0,-3.0,0.0,0.0,5.0,0.0,0.0,0.0,-14.0,0.0,0.0,58.0,4.0
2,American,Houston,128.0,5.0,0.0,-17.0,38.0,29.0,0.0,0.0,0.0,0.0,0.0,128.0,46.0
3,American,Memphis,-12.0,3.0,0.0,0.0,-3.0,0.0,0.0,0.0,6.0,0.0,0.0,-12.0,26.0
4,American,Navy,-7.0,0.0,0.0,0.0,-42.0,-22.0,0.0,0.0,0.0,0.0,-20.0,-7.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,SEC,OleMiss,30.0,30.0,20.0,-14.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,41.0,38.0
102,SEC,SouthCarolina,-56.0,-56.0,-12.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,4.0,47.0
103,SEC,Tennessee,15.0,15.0,-7.0,0.0,0.0,0.0,33.0,0.0,47.0,-3.0,0.0,0.0,57.0
104,SEC,TexasA&M,50.0,50.0,0.0,0.0,0.0,0.0,32.0,4.0,0.0,0.0,35.0,0.0,50.0
105,SEC,Vanderbilt,-204.0,-204.0,0.0,0.0,0.0,3.0,0.0,-18.0,0.0,0.0,4.0,0.0,-20.0

In [362]:
testa = allc.groupby(['BASE'])['Interleague', 'SEC', 'ACC', 'Big 12', 'CUSA', 'Independent', 'MidAmerican', 'Pac-12', 'Sun Belt', 'Big10', 'MountainWest', 'AA', 'Other'].sum()

C:\Users\vmidh\AppData\Local\Temp/ipykernel_3348/3558932559.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  testa = allc.groupby(['BASE'])['Interleague', 'SEC', 'ACC', 'Big 12', 'CUSA', 'Independent', 'MidAmerican', 'Pac-12', 'Sun Belt', 'Big10', 'MountainWest', 'AA', 'Other'].sum()

In [361]:
checkp.to_excel('ConferenceSummary2.xlsx', sheet_name='sheet1', index=False)

In [367]:
testa['points'] = testa['SEC'] + testa['ACC'] + testa['Big 12'] + testa['CUSA'] + testa['Independent'] + testa['MidAmerican'] + testa['Pac-12'] + testa['Sun Belt'] + testa['Big10'] + testa['MountainWest'] + testa['AA']

In [375]:
test3 = testa.sort_values(by =['points'], ascending = False)

In [377]:
test3.points.sum()

1009.0

In [378]:
test3

,Interleague,SEC,ACC,Big 12,CUSA,Independent,MidAmerican,Pac-12,Sun Belt,Big10,MountainWest,AA,Other,points
BASE,,,,,,,,,,,,,,
SEC,91.0,91.0,132.0,-43.0,160.0,113.0,156.0,-24.0,154.0,33.0,39.0,73.0,494.0,884.0
Big Ten,96.0,-27.0,28.0,25.0,25.0,16.0,305.0,68.0,0.0,96.0,11.0,56.0,255.0,603.0
Big 12,73.0,48.0,-18.0,73.0,93.0,18.0,0.0,37.0,5.0,-19.0,70.0,22.0,282.0,329.0
MWC,70.0,-36.0,4.0,-66.0,78.0,161.0,27.0,-50.0,0.0,-9.0,70.0,17.0,210.0,196.0
Pac-12,88.0,28.0,0.0,-33.0,0.0,-76.0,-3.0,88.0,50.0,-60.0,67.0,0.0,192.0,61.0
American,73.0,-64.0,-75.0,-16.0,32.0,45.0,58.0,0.0,0.0,-51.0,-14.0,73.0,315.0,-12.0
Ind,11.0,-104.0,-48.0,-15.0,36.0,11.0,-8.0,86.0,-18.0,-10.0,-143.0,-36.0,110.0,-249.0
CUSA,90.0,-148.0,-53.0,-89.0,90.0,-25.0,-9.0,0.0,-11.0,-19.0,-68.0,-23.0,437.0,-355.0
MAC,73.0,-146.0,-14.0,0.0,14.0,17.0,73.0,4.0,-38.0,-284.0,-19.0,-55.0,363.0,-448.0